name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Provisioning
      run: |
        set -ex
        CI=true ./init.sh
        bundle exec rake spec
    - name: Notify failure message to slack
      uses: rtCamp/action-slack-notify@v1.0.0
      if: always()
