name: Provisioning

on:
  push:
  schedule:
    - cron: 00 12 * * 1

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Provisioning
      run: |
        set -ex
        ./bin/ci/cleanup.sh
        CI=true ./init.sh
        bundle install --path vendor/bundle
        bundle exec rake spec
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() || success() }}
